/*
 * firmware/main.c - example entry to initialize HAL and control loops
 * Template: adapt clock, pinout and CubeMX generated init code.
 */

#include "stm32g4xx_hal.h"
#include "buckboost_control.h"

// Extern handles generated by CubeMX
TIM_HandleTypeDef htim_pwm;
ADC_HandleTypeDef hadc1;

void SystemClock_Config(void);

int main(void) {
    HAL_Init();
    SystemClock_Config();

    // Initialize peripherals (generated by CubeMX ideally)
    // MX_GPIO_Init();
    // MX_DMA_Init();
    // MX_ADC1_Init();
    // MX_TIM_PWM_Init();

    // Initialize buckboost module
    buckboost_init();

    // Example configuration
    buckboost_set_mode(MODE_BIDIR);
    buckboost_set_vout_ref(12.0f);
    buckboost_set_limits(10.0f, 13.2f, 2.5f, 3.6f, 60.0f, 360.0f, 100.0f);

    // Start PWM timers and ADC DMA as configured by CubeMX
    // HAL_TIM_PWM_Start(&htim_pwm, TIM_CHANNEL_1);
    // Start ADC in DMA mode etc.

    // Main loop can be largely idle; real-time loops run in timer interrupts
    while (1) {
        // process low-priority housekeeping, communication, telemetry, etc.
        HAL_Delay(100);
    }
}
